#  spring:
#    mvc:
#      pathmatch:
#        matching-strategy: ant_path_matcher

# swagger-ui custom path
springdoc:
  packagesToScan: com.dlucchesi.yhfin.controller.imp
  swagger-ui:
    path: /swagger-ui.html